### ISSUE TITLE
[Deprecated] this.pickFiles - Ember-cli 0.2.6

### ISSUE THREAD

**Issue by robertodecurnex** [Gaurav0/ember-cli-jquery-ui#10] opened 2015-06-01 14:41 UTC
Upgrading from `Ember-cli` `0.2.5` to `0.2.6` causes this deprecation warning followed by the error described blow while trying to start the `ember server`.

    [Deprecated] this.pickFiles is deprecated, please use broccoli-funnel directly instead  [addon: ember-cli-jquery-ui]

```
Cannot read property 'rebuild' of undefined
TypeError: Cannot read property 'rebuild' of undefined
    at Builder.wrapIfNecessary (/home/me/project/name/node_modules/ember-cli/node_modules/broccoli/lib/builder.js:136:18)
    at readAndReturnNodeFor (/home/me/project/name/node_modules/ember-cli/node_modules/broccoli/lib/builder.js:44:17)
    at /home/me/project/name/node_modules/ember-cli/node_modules/broccoli/lib/builder.js:92:24
    at lib$rsvp$$internal$$tryCatch (/home/me/project/name/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:489:16)
    at lib$rsvp$$internal$$invokeCallback (/home/me/project/name/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:501:17)
    at /home/me/project/name/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1095:13
    at lib$rsvp$asap$$flush (/home/me/project/name/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1290:9)
    at process._tickCallback (node.js:355:11)
```

**Comment by Gaurav0** [comment] 2015-06-01 15:06
Thanks Roberto. Looks like I have some work cut out for me.

**Comment by Gaurav0** [comment] 2015-06-01 15:59
Strangely, I'm not using pickFiles.

**Comment by yanzixiang** [comment] 2015-06-01 16:12
i catch the same error.

**Comment by Gaurav0** [comment] 2015-06-01 16:33
Still having the issue. I'd appreciate anyone's help on this.

**Comment by Gaurav0** [comment] 2015-06-01 21:04
The issue is in ember-cli. Reported here: https://github.com/ember-cli/ember-cli/issues/4205

**Comment by Gaurav0** [comment] 2015-06-02 15:14
This bug has been fixed in ember-cli master branch. Please use Ember-CLI master for now; otherwise wait for Ember-CLI 0.2.7

**Closed by Gaurav0** 2015-06-02 15:14 UTC

**Comment by Gaurav0** [comment] 2015-06-02 17:55
Ember CLI 0.2.7 is now available. Upgrading fixes this issue.
